service: rimac-appointments
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:257394458575:table/AppointmentTable
            - arn:aws:dynamodb:us-east-1:257394458575:table/AppointmentTable/index/123

functions:
  createAppointment:
    handler: dist/handlers/createAppointment.createAppointment
    events:
      - http:
          path: appointments
          method: post
          cors: true
  getAppointments:
    handler: dist/handlers/getAppointments.getAppointments
    events:
      - http:
          path: appointments/{insuredId}
          method: get
          cors: true
  appointment_pe:
    handler: dist/handlers/appointment_pe.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:257394458575:SQS_PE # Reemplaza YOUR_ACCOUNT_ID por el ID de tu cuenta
  appointment_cl:
    handler: dist/handlers/appointment_cl.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:257394458575:SQS_CL # Reemplaza YOUR_ACCOUNT_ID por el ID de tu cuenta
  updateAppointmentStatus:
    handler: dist/handlers/updateAppointmentStatus.handler
    events:
      - eventBridge:
          pattern:
            source:
              - appointment
            detail-type:
              - AppointmentConformity

resources:
  Resources:
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    SNSPE:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNS_PE_RIMAC
    SNSCL:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNS_CL_RIMAC
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: rimac-appointments-bus
