openapi: 3.0.0
info:
  title: Rimac Appointment API
  version: 1.0.0
openapi: 3.0.0
info:
  title: Rimac Appointments API
  version: 1.0.0
paths:
  /appointments:
    post:
      summary: Crear una cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                scheduleId:
                  type: string
                countryISO:
                  type: string
      responses:
        '201':
          description: Cita creada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  appointment:
                    type: object
  /appointments/{insuredId}:
    get:
      summary: Obtener citas por asegurado
      parameters:
        - name: insuredId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de citas del asegurado
          content:
            application/json:
              schema:
                type: object
                properties:
                  appointments:
                    type: array
                    items:
                      type: object
